// templates/React/src/App.tsx
import React from "react";
import logo from "./logo.svg";
import "./App.css";

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <a href="https://reactjs.org/" target="_blank">
          <img src={logo} className="App-logo" alt="logo" />
        </a>
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <p className="App-docs">Click on the Vue logos to learn more</p>
      </header>
    </div>
  );
}

export default App;

// templates/Vue/src/App.vue
<script setup lang="ts">
import HelloWorld from "./components/HelloWorld.vue";
</script>

<template>
  <div>
    <a href="https://vuejs.org/" target="_blank">
      <img src="/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vue" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
